import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import Sidebar from "@/components/Sidebar"
import { dmMono, merriweather } from "./fonts"
import { Toaster } from "sonner"
import { AuthProvider } from "@/context/AuthContext"
import { RunDialogProvider } from "@/context/RunDialogContext"
import RunDialog from "@/components/RunDialog"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${dmMono.variable} ${merriweather.variable} antialiased`}
    >
      <body>
        <AuthProvider>
          <RunDialogProvider>
            <div className="min-h-screen flex flex-col">
              <div className="flex-1 flex">
                <Sidebar />
                <main className="flex-1">{children}</main>
                <RunDialog />
              </div>
            </div>
            <Toaster position="top-right" />
          </RunDialogProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
