import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import Header from "@/components/Header"
import Sidebar from "@/components/Sidebar"
import { dmMono, merriweather } from "./fonts"
import { Toaster } from "sonner"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${dmMono.variable} ${merriweather.variable} antialiased`}
    >
      <body>
        <div className="min-h-screen flex flex-col">
          <div className="flex-1 flex">
            <Sidebar />
            <main className="flex-1">{children}</main>
          </div>
        </div>
        <Toaster position="top-right" />
      </body>
    </html>
  )
}
